name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Host
        run: echo "${{ secrets.EC2_HOST }}"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/UTS

            # 🔥 paksa sync ulang
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # stop & remove container lama
            docker ps -q | xargs -r docker stop
            docker ps -aq | xargs -r docker rm

            # build ulang tanpa cache
            docker build --no-cache -t sehat-antri .

            # jalankan container baru
            docker run -d -p 3000:3000 --env-file .env --name sehat-antri sehat-antri