script: |
  cd /home/ec2-user/UTS

  # 🔥 HAPUS REPO LAMA
  rm -rf .git

  # 🔥 CLONE ULANG (PASTI FRESH)
  git clone https://github.com/uyauyapoh/uts-kompaw.git temp

  # pindahkan isi ke folder sekarang
  cp -r temp/* .
  rm -rf temp

  docker ps -q | xargs -r docker stop
  docker ps -aq | xargs -r docker rm

  docker build --no-cache -t sehat-antri .

  docker run -d -p 3000:3000 --env-file .env --name sehat-antri sehat-antri