name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: SSH to EC2 & Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/UTS
          git pull origin main
          docker stop sehat-antri || true
          docker rm sehat-antri || true
          docker build -t sehat-antri .
          docker run -d -p 3000:3000 --env-file .env --name sehat-antri sehat-antri